Repository alexwdong/IncubatorCVProject, pull requests merged in 2020-06, with the labels that each got.

#8 Pull Request for feature engineering
  src/feature_engineering.py
  src/utils.py
Labels: Feature Engineering

#6 Basic CNN Architecture WIP(Not Ready for Merge)
  Basic_CNN_Architecture.py
Labels: Model

#7 pipeline version 1
  main_two.py
  train_valid.py
Labels: Infrastructure/Pipeline
